#!/bin/bash

# To know hostname of the system
HOSTNAME=$(hostname)

# For getting OS name of system
source /etc/os-release
OS=$PRETTY_NAME

# To know Uptime
UPTIME=$(uptime -p)

# For the hardware information like model, speed, ram, disk and video card of cpu
CPU=$(lshw -class processor | awk '/product/ {print $2, $3, $4, $5}')
CPU_SPEED=$(lscpu | awk '/^CPU MHz/ {print $3}')
CPU_MAX_SPEED=$(lscpu | awk '/^CPU max MHz/ {print $4}')
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(lsblk -io NAME,SIZE,MODEL | awk '$1!="NAME" {print $1,$2" ("$3")"}')
VIDEO=$(lspci | grep -i vg)

# To get network information such as ip address in CIDR format, host address, gateway, DNS server, and interfacename
FQDN=$(hostname -f)
HOST_ADDRESS=$(ip -o -4 addr show | awk '/inet / {print $4}')
GATEWAY_IP=$(ip r | awk '/default / {print $3}')
DNS_SERVER=$(grep -i nameserver /etc/resolv.conf | awk '{print $2}')
INTERFACE=$(lshw -C network | awk '/logical name/ {print $NF; exit}')
IP_ADDRESS=$(ip -o -4 addr show  | awk ' {print $4}')

# Information of system Status
USERS=$(who | awk '{print $1}')
DISK_SPACE=$(df -h --output=target,avail | awk '$1!~"^tmpfs$" {print $1" "$2}')
PROCESS_COUNT=$(ps aux --no-headers | wc -l)
LOAD_AVERAGES=$(uptime | awk -F': ' '{print $NF}')
MEMORY_ALLOC=$(free -h | awk '/^Mem:/ {print $3"/"$2}')
LISTENING_PORTS=$(ss -tunl | awk 'NR>1 {print $5}')
UFW_RULES=$(sudo ufw show raw | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {print $0}')

# For output of the system report
cat <<EOF

System Report generated by $USER, $DATE

System Information
-------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
----------------------
CPU: $CPU
Speed: $CPU_SPEED MHz (Max: $CPU_MAX_SPEED MHz)
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO

Network Information
---------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

InterfaceName: $INTERFACE
IP Address: $IP_ADDRESS

System Status
--------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOC
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES

EOF
